<?php
session_start();
unset($_SESSION["email"]);
unset($_SESSION["uname"]);
unset($_SESSION["fname"]);
unset($_SESSION["status"]);
unset($_SESSION['logged_in']);  
session_destroy();
header("Location:index.php");
?>